name = "aiken/aiken_bilinear_accumulator"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken/aiken_bilinear_accumulator'"

[repository]
user = "aiken"
project = "aiken_bilinear_accumulator"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
